name: 'Deploy gh-pages PR build'
description: Deploys a gh-pages site from a PR build
inputs:
  token:
    description: 'PAT with admin access to repo'
    required: true
  
  actor:
    description: 'PR author'
    default: ${{ github.actor }}
  buildFolder:
    description: 'Build Folder'
    default: dist
  deploy:
    description: "Branch with page deployment"
    default: gh-pages
  main:
    description: "Branch with raw code"
    default: main
  prTitle:
    description: "Title for deployment PR"
    default: ${{ github.event.pull_request.title }}
  repository:
    description: "Repository name with owner"
    default: ${{ github.repository }}

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ACTOR: ${{ inputs.actor }}
    BUILD: ${{ inputs.buildFolder }}
    GH_TOKEN: ${{ inputs.token }}
    REPO: ${{ inputs.repository }}
    MAIN: ${{ inputs.main }}
    DEPLOY: ${{ inputs.deploy }}
    PR_TITLE: ${{ inputs.prTitle }}
