name: Deploy GitHub Pages PR build
description: Deploys a gh-pages site from a PR build
inputs:
  token:
    description: 'PAT with admin access to repo'
    default: ${{ github.token }}

  buildFolder:
    description: 'Build Folder'
    default: dist
  deploy:
    description: "Branch with page deployment"
    default: gh-pages
  main:
    description: "Branch with raw code"
    default: ${{ github.ref_name }}
  prTitle:
    description: "Title for deployment PR"
    default: Deploy PR for commit
  repository:
    description: "Repository name with owner"
    default: ${{ github.repository }}

runs:
  using: 'docker'
  image: 'Dockerfile'