name: 'Deploy gh-pages PR build'
description: Deploys a gh-pages site from a PR build
inputs:
  token:
    description: 'PAT with admin access to repo'
    required: true
  merge:
    description: 'Whether or not to merge PR'
    required: false
    default: 'false'
    
  repository:
    description: 'Repository name with owner'
    default: ${{ github.repository }}
  prNumber:
    description: 'PR Number'
    default: ${{ github.event.pull_request.number }}
    

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    REPO: ${{ inputs.repository }}
    TOKEN: ${{ inputs.token }}
    MERGE: ${{ inputs.merge }}
    PR_NUMBER: ${{ inputs.prNumber }}
