extends: default
yaml-files:
  - "*.yml"
rules:
  braces:
    level: warning
    min-spaces-inside: 1
    max-spaces-inside: 1
    min-spaces-inside-empty: 1
    max-spaces-inside-empty: 1
  brackets:
    level: warning
    min-spaces-inside: 1
    max-spaces-inside: 1
    min-spaces-inside-empty: 1
    max-spaces-inside-empty: 1
  colons:
    level: warning
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    level: warning
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1
  comments: disable
  comments-indentation: disable
  document-end: disable
  document-start: disable
  empty-lines:
    level: warning
    max: 2
    max-start: 0
    max-end: 0
  hyphens:
    level: warning
    max-spaces-after: 1
  indentation:
    level: error
    spaces: consistent
    indent-sequences: consistent
  line-length:
    level: warning
    max: 100
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  new-line-at-end-of-file: disable
  new-lines: disable
  octal-values: disable
  quoted-strings: disable
  trailing-spaces: disable