name: Lint
on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Lint changes against ${{ inputs.default_branch }}
        uses: github/super-linter/slim@v4.9.7
        env: 
          DEFAULT_BRANCH: main
          VALIDATE_CSS: true
          VALIDATE_HTML: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_TYPESCRIPT_STANDARD: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_YAML: true
