name: Release
on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  release:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
    - name: Release on PR Merge
      uses: ajbarga/release-management@main
      with:
        token: ${{ secrets.MY_PAT }}
        
